pipeline:
  name: starci
  identifier: starci
  projectIdentifier: IVAN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubdude
        repoName: harnessdeveloperhub
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: welcome
